import type { Metadata } from 'next'
import PredictiveAnalyticsAgentPage from '@/src/pages/vertex-ai/operations/PredictiveAnalyticsAgentPage'

export const metadata: Metadata = {
  title: 'Predictive Analytics Agent — Vertex AI Forecasting & Prediction',
  description: 'Custom prediction pipelines on Vertex AI — demand forecasting, churn prediction, or equipment failure detection — with Gemini explaining predictions in plain language on Google Cloud.',
  alternates: { canonical: 'https://kovil.ai/vertex-ai/operations/predictive-analytics-agent' },
  keywords: ['predictive analytics GCP', 'Vertex AI prediction', 'demand forecasting GCP', 'churn prediction Vertex AI', 'predictive maintenance GCP', 'BigQuery ML forecasting', 'Vertex AI AutoML', 'Gemini predictive analytics', 'Google Cloud ML prediction', 'Vertex AI time series', 'predictive analytics AI agent', 'GCP forecasting agent'],
  openGraph: {
    type: 'website',
    title: 'Predictive Analytics Agent — Vertex AI & BigQuery ML | Kovil AI',
    description: 'Custom prediction pipelines on Vertex AI — demand forecasting, churn prediction, equipment failure detection — with Gemini explaining predictions in plain language.',
    url: 'https://kovil.ai/vertex-ai/operations/predictive-analytics-agent',
    siteName: 'Kovil AI',
    images: [{ url: 'https://kovil.ai/og-vertex-ai.png', width: 1200, height: 630, alt: 'Predictive Analytics Agent — Kovil AI' }],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Predictive Analytics Agent | Kovil AI Vertex AI',
    description: 'Demand forecasting, churn prediction, equipment failure detection on Vertex AI. Gemini explains predictions in plain language.',
    images: ['https://kovil.ai/og-vertex-ai.png'],
  },
}

const serviceSchema = {
  '@context': 'https://schema.org',
  '@type': 'Service',
  name: 'Predictive Analytics Agent',
  description: 'Custom prediction pipelines on Vertex AI — demand forecasting, churn prediction, equipment failure detection — with Gemini narrating predictions in plain language and triggering downstream actions.',
  provider: { '@type': 'Organization', name: 'Kovil AI', url: 'https://kovil.ai', logo: 'https://kovil.ai/kovil-logo-symbol-orange.webp' },
  serviceType: 'Vertex AI Implementation',
  url: 'https://kovil.ai/vertex-ai/operations/predictive-analytics-agent',
  areaServed: ['New York', 'Austin', 'United States', 'United Kingdom'],
}

const faqSchema = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: [
    { '@type': 'Question', name: 'What prediction use cases does the Vertex AI predictive agent cover?', acceptedAnswer: { '@type': 'Answer', text: 'Common use cases we implement on Vertex AI include: demand forecasting for retail and manufacturing (SKU-level, using BigQuery ML ARIMA Plus or Vertex AI AutoML Forecasting); customer churn prediction for SaaS, telecoms, and financial services (binary classification using boosted trees or neural networks); equipment failure and predictive maintenance for manufacturing and utilities (time-series anomaly detection and remaining useful life estimation); credit risk scoring for financial services; and inventory optimisation. Each model is trained on your historical data and tuned for your specific domain.' } },
    { '@type': 'Question', name: 'How does Gemini explain the predictions?', acceptedAnswer: { '@type': 'Answer', text: 'Once a prediction is generated by the Vertex AI or BigQuery ML model, we pass the prediction output — including the probability score, key feature values (e.g., "customer has not logged in for 45 days", "machine vibration is 3.2σ above normal"), and Shapley feature importance values — to Gemini as structured context. Gemini generates a plain-language explanation tailored to the business audience: "This customer is 87% likely to churn in the next 30 days. The key drivers are their 6-week login gap, two unresolved support tickets, and reduced usage of the core feature." The explanation is attached to each prediction record in BigQuery and surfaced in dashboards or alerts.' } },
    { '@type': 'Question', name: 'How do we know if the predictions are accurate enough to act on?', acceptedAnswer: { '@type': 'Answer', text: 'We implement an evaluation framework as part of every predictive analytics engagement: during model development, we measure precision, recall, F1, AUC-ROC (for classification) or MAE, MAPE, RMSE (for forecasting) on held-out test data. In production, we implement continuous monitoring using Vertex AI Model Monitoring — tracking prediction distribution drift, feature drift, and ground truth accuracy as outcomes become available. We configure alerting thresholds so that when model performance degrades beyond a configurable threshold, the team is notified and retraining is triggered automatically via Vertex AI Pipelines.' } },
    { '@type': 'Question', name: 'Can the predictive agent trigger automated actions based on predictions?', acceptedAnswer: { '@type': 'Answer', text: 'Yes. We build the full prediction-to-action pipeline: high-churn-risk predictions trigger personalised retention campaigns via your marketing platform (Salesforce Marketing Cloud, HubSpot, Braze); high equipment failure risk predictions trigger work orders in your CMMS (SAP PM, Maximo, ServiceNow Field Service); demand forecast outputs update safety stock levels in your ERP automatically. Actions are configurable by confidence threshold — predictions above a threshold trigger automated actions, while lower-confidence predictions route to a human review queue with Gemini narration. All triggered actions are logged in Cloud Audit Logs for traceability.' } },
  ],
}

const breadcrumbSchema = {
  '@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  itemListElement: [
    { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://kovil.ai' },
    { '@type': 'ListItem', position: 2, name: 'Vertex AI', item: 'https://kovil.ai/vertex-ai' },
    { '@type': 'ListItem', position: 3, name: 'Operations', item: 'https://kovil.ai/vertex-ai/operations' },
    { '@type': 'ListItem', position: 4, name: 'Predictive Analytics Agent', item: 'https://kovil.ai/vertex-ai/operations/predictive-analytics-agent' },
  ],
}

export default function Page() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(serviceSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />
      <PredictiveAnalyticsAgentPage />
    </>
  )
}
