// Generated by scratch/process-logos.py — real platform logos (trimmed). `bg` = full-bleed colored logo.
export interface PlatformLogo { src: string; aspect: number; bg: string | null }

export const PLATFORM_LOGOS: Record<string, PlatformLogo> = {
  "activecampaign": {
    "src": "/platform-logos/activecampaign.webp",
    "aspect": 1.0,
    "bg": null
  },
  "acumatica": {
    "src": "/platform-logos/acumatica.webp",
    "aspect": 1.0,
    "bg": null
  },
  "adobe-experience-manager": {
    "src": "/platform-logos/adobe-experience-manager.webp",
    "aspect": 1.0,
    "bg": null
  },
  "algolia": {
    "src": "/platform-logos/algolia.webp",
    "aspect": 1.0,
    "bg": null
  },
  "asana": {
    "src": "/platform-logos/asana.webp",
    "aspect": 1.081,
    "bg": null
  },
  "atlassian": {
    "src": "/platform-logos/atlassian.webp",
    "aspect": 0.997,
    "bg": null
  },
  "auth0-okta": {
    "src": "/platform-logos/auth0-okta.webp",
    "aspect": 1.0,
    "bg": null
  },
  "boomi": {
    "src": "/platform-logos/boomi.webp",
    "aspect": 1.0,
    "bg": null
  },
  "braze": {
    "src": "/platform-logos/braze.webp",
    "aspect": 1.0,
    "bg": null
  },
  "contentful": {
    "src": "/platform-logos/contentful.webp",
    "aspect": 0.884,
    "bg": null
  },
  "freshworks": {
    "src": "/platform-logos/freshworks.webp",
    "aspect": 1.0,
    "bg": null
  },
  "hubspot": {
    "src": "/platform-logos/hubspot.webp",
    "aspect": 0.956,
    "bg": null
  },
  "klaviyo": {
    "src": "/platform-logos/klaviyo.webp",
    "aspect": 1.461,
    "bg": null
  },
  "marketo": {
    "src": "/platform-logos/marketo.webp",
    "aspect": 0.858,
    "bg": null
  },
  "microsoft-dynamics-365": {
    "src": "/platform-logos/microsoft-dynamics-365.webp",
    "aspect": 0.742,
    "bg": null
  },
  "monday": {
    "src": "/platform-logos/monday.webp",
    "aspect": 1.682,
    "bg": null
  },
  "mulesoft": {
    "src": "/platform-logos/mulesoft.webp",
    "aspect": 1.003,
    "bg": null
  },
  "netsuite": {
    "src": "/platform-logos/netsuite.webp",
    "aspect": 1.043,
    "bg": null
  },
  "odoo": {
    "src": "/platform-logos/odoo.webp",
    "aspect": 1.333,
    "bg": "#a24689"
  },
  "pipedrive": {
    "src": "/platform-logos/pipedrive.webp",
    "aspect": 1.0,
    "bg": "#017737"
  },
  "quickbooks": {
    "src": "/platform-logos/quickbooks.webp",
    "aspect": 1.0,
    "bg": null
  },
  "sage-intacct": {
    "src": "/platform-logos/sage-intacct.webp",
    "aspect": 1.0,
    "bg": null
  },
  "salesforce": {
    "src": "/platform-logos/salesforce.webp",
    "aspect": 1.429,
    "bg": null
  },
  "servicenow": {
    "src": "/platform-logos/servicenow.webp",
    "aspect": 1.118,
    "bg": null
  },
  "shopify-plus": {
    "src": "/platform-logos/shopify-plus.webp",
    "aspect": 0.881,
    "bg": null
  },
  "smartsheet": {
    "src": "/platform-logos/smartsheet.webp",
    "aspect": 1.0,
    "bg": null
  },
  "strapi": {
    "src": "/platform-logos/strapi.webp",
    "aspect": 0.978,
    "bg": null
  },
  "stripe": {
    "src": "/platform-logos/stripe.webp",
    "aspect": 1.0,
    "bg": null
  },
  "twilio": {
    "src": "/platform-logos/twilio.webp",
    "aspect": 1.0,
    "bg": null
  },
  "uipath": {
    "src": "/platform-logos/uipath.webp",
    "aspect": 1.0,
    "bg": null
  },
  "webflow": {
    "src": "/platform-logos/webflow.webp",
    "aspect": 1.607,
    "bg": null
  },
  "wrike": {
    "src": "/platform-logos/wrike.svg",
    "aspect": 1.6,
    "bg": null
  },
  "xero": {
    "src": "/platform-logos/xero.webp",
    "aspect": 1.0,
    "bg": null
  },
  "zendesk": {
    "src": "/platform-logos/zendesk.webp",
    "aspect": 1.0,
    "bg": null
  },
  "zoho-one": {
    "src": "/platform-logos/zoho-one.webp",
    "aspect": 2.323,
    "bg": null
  },
  "zuora": {
    "src": "/platform-logos/zuora.webp",
    "aspect": 1.0,
    "bg": "#103426"
  }
}
